object Versions {
    const val retrofit = "2.9.0"
    const val navigation = "2.7.4"
    const val compose = "2.6.2"
    const val navCompose = "1.0.0"
    const val coil = "2.4.0"
    const val jsoup = "1.16.2"
    const val htmlUnitCssParser = "3.7.0"
    const val materialExtendedIcons = "1.5.4"
    const val dagger = "2.49"

    const val agp = "8.4.0-alpha08"
    const val kotlin = "1.9.0"
    const val coreKtx = "1.12.0"
    const val junit = "4.13.2"
    const val androidxTestExtJunit = "1.1.5"
    const val espressoCore = "3.5.1"
    const val lifecycleRuntimeKtx = "2.6.2"
    const val activityCompose = "1.8.0"
    const val composeBom = "2023.08.00"
    const val appcompat = "1.6.1"
    const val material = "1.10.0"
}